apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
  labels:
    app: app-one
  namespace: fluxing
spec:
  selector:
    matchLabels:
      app: app-one
    replicas: 2
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    template:
      metadata:
        labels:
          app: app-one
      spec:
        containers:
        - name: app-one
          image: app-one:0.0.1
          ports:
          - containerPort: 5000
          volumeMounts:
          - name: app-one-config
            mountPath: /configs
        volumes:
        - name: app-one-config
          configMap:
            name: app-one-config