apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-one
  namespace: fluxing
spec:
  interval: 15m
  path: "./kubernetes/fluxcd/repositories/app-one/deploy"
  prune: true
  sourceRef:
      kind: GitRepository
      name: app-one
